### ISSUE TITLE
[BE/FE] - APIs calls structure from FE to BE & viceversa

### ISSUE THREAD

**Issue by davegabe** [CUPChain/webapp#1]
Define the structure of the json provided from FE to BE and viceversa

**Comment by davegabe** [comment]
Ho definito una struttura semplicistica dei dati che mostro all'utente attraverso questi tipi come prima bozza
https://github.com/CUPChain/webapp/blob/main/frontend/src/types.tsx

**Comment by AntoAndGar** [comment]
@davegabe  okay quindi ti serviranno lato BE delle query al DB dove ti passo un json con quelle 3 strutture? Oppure roba maggiormente granulare che assembli tu?

**Comment by davegabe** [comment]
Un JSON con queste strutture per il momento va bene
