### ISSUE TITLE
[BE] - Serving React App through Flask

### ISSUE THREAD

**Issue by AntoAndGar** [CUPChain/webapp#2]

**Comment by AntoAndGar** [comment]
@davegabe il mio backend dagli ultimi update del FE non è più capace di servire le pagine prenotazione, appuntamenti ecc., solo la home e la login vengono visulizzate correttamente

**Comment by davegabe** [comment]
Ho qualche problema ad avviare la parte di backend per verificare il funzionamento.
Sia usando `python -m app` che `python app.py`  ho problemi del tipo: `ImportError: attempted relative import with no known parent package`.
A quanto ho visto potrebbe essere che le nuove versioni di python sono un po' più rigide sugli import (uso Python 3.11).
Se puoi fai un piccolo readme file dove scrivi i comandi per runnare che usi e che versione python usi.
